export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const CATEGOIRES_ERROR  = 'CATEGOIRES_ERROR'

export const GET_SERVICE  = 'GET_SERVICE'
export const SERVICE_ERROR  = 'SERVICE_ERROR'

export const SET_FORMDATA  = 'SET_FORMDATA'
export const SET_PREPAYMENT_DATA = 'SET_PREPAYMENT_DATA'

export const SET_SERVICE = 'SET_SERVICE'

export const SEND_PREPAYMENT_REQUEST = 'SEND_PREPAYMENT_REQUEST'
export const PREPAYMENT_REQUEST_ERROR = 'PREPAYMENT_REQUEST_ERROR'
export const CLEAR_PREPAYMENT_DATA = 'CLEAR_PREPAYMENT_DATA'
export const SEND_SMS_CONFIRMATION = 'SEND_SMS_CONFIRMATION'
export const CONFIRM_SMS_CODE = 'CONFIRM_SMS_CODE'
